<a href="https://colab.research.google.com/github/sselgrad23/Pandas-Tutorial-For-Beginners/blob/main/pandas_tutorial_lesson_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas DataFrame Operations: Lesson 3

In [1]:
import pandas as pd

In [2]:
coffee = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv')

### Viewing Data: `head()`, `tail()`, and `sample()`

In [3]:
coffee.head() # First five rows

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [4]:
coffee # Whole dataframe

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

You can pass a value in head or tail to view the first/last x items in the dataframe:

In [5]:
coffee.tail(2) # Last 2 items

       Day Coffee Type  Units Sold
12  Sunday    Espresso          45
13  Sunday       Latte          35

In [6]:
coffee.head(10) # First 10 items

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35
5  Wednesday       Latte          25
6   Thursday    Espresso          40
7   Thursday       Latte          30
8     Friday    Espresso          45
9     Friday       Latte          35

Depending on the IDE/editor that you use, just giving the name of the dataframe may be enough to view all of it. However, you might need to do one of the following:

In [7]:
print(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [8]:
display(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

You can randomly sample a certain number of rows by using df.sample. If you want to deterministically sample a set number of rows, you can set a seed using random_state.

In [9]:
coffee.sample(10, random_state=42) # Randomly samples 10 (or whatever number you choose) rows

          Day Coffee Type  Units Sold
9      Friday       Latte          35
11   Saturday       Latte          35
0      Monday    Espresso          25
12     Sunday    Espresso          45
5   Wednesday       Latte          25
8      Friday    Espresso          45
2     Tuesday    Espresso          30
1      Monday       Latte          15
13     Sunday       Latte          35
4   Wednesday    Espresso          35

### Accessing Data with `loc` and `iloc`

loc can be used to access specific rows and columns using labels or a boolean array. For example, we can access the first row of our dataframe by doing the following:

In [10]:
coffee.loc[0]

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

loc is inclusive of the upper index, as we can see in the following:

In [11]:
coffee.loc[5:12] # Using slicing

          Day Coffee Type  Units Sold
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45

In [12]:
coffee.loc[:, ["Day", "Units Sold"]]

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

We can use a boolean condition too. For example, with the following code, we can display only those rows where more than 20 units were sold:

In [13]:
coffee.loc[coffee["Units Sold"] > 20]

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
2     Tuesday    Espresso          30
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

iloc is used to select data by its integer position. It's helpful when you want to access rows or columns based on their numerical index, much like how you would access elements in a list or array.

In [14]:
coffee.iloc[0] # Selects first row

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [15]:
coffee.iloc[:, 0] # Selects first column

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: object

Note that iloc is not inclusive of the upper index. We select the rows from index 2 up to BUT NOT INCLUDING 5, and only the columns at indexes 0 and 2

In [16]:
coffee.iloc[2:5, [0,2]]

         Day  Units Sold
2    Tuesday          30
3    Tuesday          20
4  Wednesday          35

#### Understanding the DataFrame Index

We can see that our dataframe has the default integer index. We have 14 rows, going from 0 to 13, with a step of 1.

In [17]:
coffee.index # Shows the index of the DataFrame

RangeIndex(start=0, stop=14, step=1)

We can access specific columns by name in different ways:

In [18]:
coffee.Day

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: object

In [19]:
coffee["Units Sold"]

0     25
1     15
2     30
3     20
4     35
5     25
6     40
7     30
8     45
9     35
10    45
11    35
12    45
13    35
Name: Units Sold, dtype: int64

#### Overwriting the Default Index

We can overwrite the default indexing of our dataframe. First I make a deep copy, for demonstrative purposes:

In [20]:
coffee_copy = coffee.copy(deep=True)

Let's set the 'Day' column as the new index.

In [21]:
coffee_copy.set_index('Day', inplace=True)

In [22]:
coffee_copy.head()

          Coffee Type  Units Sold
Day
Monday       Espresso          25
Monday          Latte          15
Tuesday      Espresso          30
Tuesday         Latte          20
Wednesday    Espresso          35

With 'Day' as the index, `loc` can now directly access rows using the day names. For example, let's try to get all entries for 'Monday'.

In [23]:
coffee_copy.loc['Monday']

       Coffee Type  Units Sold
Day
Monday    Espresso          25
Monday       Latte          15

In [24]:
coffee_copy.loc['Monday':'Thursday', 'Units Sold']

Day
Monday       25
Monday       15
Tuesday      30
Tuesday      20
Wednesday    35
Wednesday    25
Thursday     40
Thursday     30
Name: Units Sold, dtype: int64

iloc still relies on integer positions:

In [25]:
coffee_copy.iloc[0,:]

Coffee Type    Espresso
Units Sold           25
Name: Monday, dtype: object

In [26]:
coffee_copy.iloc[:, :]

          Coffee Type  Units Sold
Day
Monday       Espresso          25
Monday          Latte          15
Tuesday      Espresso          30
Tuesday         Latte          20
Wednesday    Espresso          35
Wednesday       Latte          25
Thursday     Espresso          40
Thursday        Latte          30
Friday       Espresso          45
Friday          Latte          35
Saturday     Espresso          45
Saturday        Latte          35
Sunday       Espresso          45
Sunday          Latte          35

##### `iloc` Behavior with a Custom Index

If you want 'Day' to be treated as a regular column again so you can select it with iloc, you would need to reset_index() on your DataFrame. Let's create a new DataFrame coffee_reset for this demonstration:

In [27]:
coffee_reset = coffee_copy.reset_index()
print(coffee_reset.head())

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

'Day' is a regular column again:

In [28]:
coffee_reset.iloc[:, :]

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [29]:
coffee_reset.iloc[:, 0] # Selects the 'Day' column

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: object

### Modifying Data in a DataFrame

We can also modify individual or several cells:

In [30]:
coffee.loc[2, "Units Sold"] = 100

In [31]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso         100
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [32]:
coffee.loc[3:5, "Units Sold"] = 15

In [33]:
coffee.head(7)

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso         100
3    Tuesday       Latte          15
4  Wednesday    Espresso          15
5  Wednesday       Latte          15
6   Thursday    Espresso          40

We can also get individual cells more efficiently using at and iat. We can't use them to get multiple values, though.

In [34]:
coffee.at[2, "Units Sold"]

np.int64(100)

In [35]:
coffee.iat[2,2]

np.int64(100)

## Sorting Values

We can also sort our values. We can provide column names. By default, values will be ascending:

In [36]:
coffee.sort_values(by="Units Sold")

          Day Coffee Type  Units Sold
1      Monday       Latte          15
3     Tuesday       Latte          15
5   Wednesday       Latte          15
4   Wednesday    Espresso          15
0      Monday    Espresso          25
7    Thursday       Latte          30
11   Saturday       Latte          35
9      Friday       Latte          35
13     Sunday       Latte          35
6    Thursday    Espresso          40
10   Saturday    Espresso          45
8      Friday    Espresso          45
12     Sunday    Espresso          45
2     Tuesday    Espresso         100

ascending = 0 is equivalent to ascending = False

In [37]:
coffee.sort_values(by=["Units Sold", "Coffee Type"], ascending=[0,1])

          Day Coffee Type  Units Sold
2     Tuesday    Espresso         100
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
7    Thursday       Latte          30
0      Monday    Espresso          25
4   Wednesday    Espresso          15
1      Monday       Latte          15
3     Tuesday       Latte          15
5   Wednesday       Latte          15

### Iterating Through Rows (`iterrows`)

We can also iterate row by row with a for loop, but this is not recommended as we will lose some of the memory/performance benefits of pandas.

In [38]:
for idx, row in coffee.iterrows():
  if idx > 5:
    break
  print(idx, row, "\n")

0 Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

1 Day            Monday
Coffee Type     Latte
Units Sold         15
Name: 1, dtype: object

2 Day             Tuesday
Coffee Type    Espresso
Units Sold          100
Name: 2, dtype: object

3 Day            Tuesday
Coffee Type      Latte
Units Sold          15
Name: 3, dtype: object

4 Day            Wednesday
Coffee Type     Espresso
Units Sold            15
Name: 4, dtype: object

5 Day            Wednesday
Coffee Type        Latte
Units Sold            15
Name: 5, dtype: object