<a href="https://colab.research.google.com/github/sselgrad23/Pandas-Tutorial-For-Beginners/blob/main/pandas_tutorial_lesson_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# `.shift()`, `.rank()`, `.cumsum()`, and `.rolling()`

In [1]:
import pandas as pd
import numpy as np

In [2]:
coffee = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv')
coffee['price'] = np.where(coffee['Coffee Type'] == 'Espresso', 3.99, 5.99)
coffee['revenue'] = coffee['Units Sold'] * coffee['price']
latte = coffee[coffee['Coffee Type'] == 'Latte'].copy()
coffee.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso          25   3.99    99.75
1     Monday       Latte          15   5.99    89.85
2    Tuesday    Espresso          30   3.99   119.70
3    Tuesday       Latte          20   5.99   119.80
4  Wednesday    Espresso          35   3.99   139.65

Let's compare today's revenue with yesterday's revenue for both coffee types. We can do that using `shift()`:

In [3]:
coffee['yesterday_revenue'] = coffee['revenue'].shift(2)

In [4]:
coffee

          Day Coffee Type  Units Sold  price  revenue  yesterday_revenue
0      Monday    Espresso          25   3.99    99.75                NaN
1      Monday       Latte          15   5.99    89.85                NaN
2     Tuesday    Espresso          30   3.99   119.70              99.75
3     Tuesday       Latte          20   5.99   119.80              89.85
4   Wednesday    Espresso          35   3.99   139.65             119.70
5   Wednesday       Latte          25   5.99   149.75             119.80
6    Thursday    Espresso          40   3.99   159.60             139.65
7    Thursday       Latte          30   5.99   179.70             149.75
8      Friday    Espresso          45   3.99   179.55             159.60
9      Friday       Latte          35   5.99   209.65             179.70
10   Saturday    Espresso          45   3.99   179.55             179.55
11   Saturday       Latte          35   5.99   209.65             209.65
12     Sunday    Espresso          45   3.99   179.55             179.55
13     Sunday       Latte          35   5.99   209.65             209.65

We can find the percent change between yesterday and today's revenue:

In [5]:
coffee['pct_change'] = coffee['revenue'] / coffee['yesterday_revenue'] * 100
coffee

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change
0,Monday,Espresso,25,3.99,99.75,NaN,NaN
1,Monday,Latte,15,5.99,89.85,NaN,NaN
2,Tuesday,Espresso,30,3.99,119.70,99.75,120.000000
3,Tuesday,Latte,20,5.99,119.80,89.85,133.333333
4,Wednesday,Espresso,35,3.99,139.65,119.70,116.666667
5,Wednesday,Latte,25,5.99,149.75,119.80,125.000000
6,Thursday,Espresso,40,3.99,159.60,139.65,114.285714
7,Thursday,Latte,30,5.99,179.70,149.75,120.000000
8,Friday,Espresso,45,3.99,179.55,159.60,112.500000
9,Friday,Latte,35,5.99,209.65,179.70,116.666667
10,Saturday,Espresso,45,3.99,179.55,179.55,100.000000
11,Saturday,Latte,35,5.99,209.65,209.65,100.000000
12,Sunday,Espresso,45,3.99,179.55,179.55,100.000000
13,Sunday,Latte,35,5.99,209.65,209.65,100.000000

Let's go to our bios dataset and rank the athletes by height:

In [6]:
bios = pd.read_csv('https://github.com/KeithGalli/complete-pandas-tutorial/raw/refs/heads/master/data/bios.csv')
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [7]:
bios['height_rank'] = bios['height_cm'].rank(ascending=False)
bios.sort_values(['height_rank'])

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_rank
89070,89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN,1.0
6978,7013,Arvydas Sabonis,1964-12-19,Kaunas,Kaunas,LTU,Lithuania Soviet Union,223.0,122.0,NaN,2.5
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN,2.5
5673,5696,Gunther Behnke,1963-01-19,Leverkusen,Nordrhein-Westfalen,GER,Germany,221.0,114.0,NaN,5.0
89075,89787,Roberto Dueñas,1975-11-01,Madrid,Madrid,ESP,Spain,221.0,137.0,NaN,5.0
...,...,...,...,...,...,...,...,...,...,...,...
145490,149217,Sin Ye-Chan,1995-06-13,NaN,NaN,NaN,Republic of Korea,NaN,NaN,NaN,NaN
145491,149218,Matthew Wepke,1989-12-05,NaN,NaN,NaN,Jamaica,NaN,NaN,NaN,NaN
145492,149219,Carlos García-Ordóñez,1927-04-24,La Habana (Havana),Ciudad de La Habana,CUB,Cuba,NaN,NaN,2019-11-24,NaN
145493,149220,Landysh Falyakhova,1998-08-31,Dva Polya Artash,Respublika Tatarstan,RUS,ROC,NaN,NaN,NaN,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,NaN

Let's go back to our coffee dataframe. We can calculate cumulative revenue using `.cumsum()`:

In [8]:
coffee['cumulative_revenue'] = coffee['revenue'].cumsum()
coffee

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change,cumulative_revenue
0,Monday,Espresso,25,3.99,99.75,NaN,NaN,99.75
1,Monday,Latte,15,5.99,89.85,NaN,NaN,189.60
2,Tuesday,Espresso,30,3.99,119.70,99.75,120.000000,309.30
3,Tuesday,Latte,20,5.99,119.80,89.85,133.333333,429.10
4,Wednesday,Espresso,35,3.99,139.65,119.70,116.666667,568.75
5,Wednesday,Latte,25,5.99,149.75,119.80,125.000000,718.50
6,Thursday,Espresso,40,3.99,159.60,139.65,114.285714,878.10
7,Thursday,Latte,30,5.99,179.70,149.75,120.000000,1057.80
8,Friday,Espresso,45,3.99,179.55,159.60,112.500000,1237.35
9,Friday,Latte,35,5.99,209.65,179.70,116.666667,1447.00
10,Saturday,Espresso,45,3.99,179.55,179.55,100.000000,1626.55
11,Saturday,Latte,35,5.99,209.65,209.65,100.000000,1836.20
12,Sunday,Espresso,45,3.99,179.55,179.55,100.000000,2015.75
13,Sunday,Latte,35,5.99,209.65,209.65,100.000000,2225.40

We can get a rolling sum of the number of lattes sold over the past 3 days:

In [9]:
latte['3day'] = latte['Units Sold'].rolling(3).sum()
latte

          Day Coffee Type  Units Sold  price  revenue   3day
1      Monday       Latte          15   5.99    89.85    NaN
3     Tuesday       Latte          20   5.99   119.80    NaN
5   Wednesday       Latte          25   5.99   149.75   60.0
7    Thursday       Latte          30   5.99   179.70   75.0
9      Friday       Latte          35   5.99   209.65   90.0
11   Saturday       Latte          35   5.99   209.65  100.0
13     Sunday       Latte          35   5.99   209.65  105.0