<a href="https://colab.research.google.com/github/sselgrad23/Pandas-Tutorial-For-Beginners/blob/main/pandas_tutorial_lesson_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Adding and Removing Columns

In [1]:
import pandas as pd
import numpy as np

In [2]:
coffee = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv')

We can easily add new columns:

In [3]:
coffee['price'] = 4.99
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   4.99
1     Monday       Latte          15   4.99
2    Tuesday    Espresso          30   4.99
3    Tuesday       Latte          20   4.99
4  Wednesday    Espresso          35   4.99

In [4]:
coffee['Coffee Type'].nunique()

2

In [5]:
coffee['Coffee Type'].unique()

array(['Espresso', 'Latte'], dtype=object)

We can also incorporate numpy. For example, we use np.where to set the new price of Espressos to 3.99 and the new price of all other coffee types to 5.99:

In [6]:
coffee['new_price'] = np.where(coffee['Coffee Type'] == 'Espresso', 3.99, 5.99)
coffee.head()

         Day Coffee Type  Units Sold  price  new_price
0     Monday    Espresso          25   4.99       3.99
1     Monday       Latte          15   4.99       5.99
2    Tuesday    Espresso          30   4.99       3.99
3    Tuesday       Latte          20   4.99       5.99
4  Wednesday    Espresso          35   4.99       3.99

We can also drop individual rows:

In [7]:
coffee_drop_0 = coffee.drop(0, axis=0)

In [8]:
coffee_drop_0.head()

         Day Coffee Type  Units Sold  price  new_price
1     Monday       Latte          15   4.99       5.99
2    Tuesday    Espresso          30   4.99       3.99
3    Tuesday       Latte          20   4.99       5.99
4  Wednesday    Espresso          35   4.99       3.99
5  Wednesday       Latte          25   4.99       5.99

In [9]:
drop_price = coffee.drop(columns=['price'])

In [10]:
drop_price.head()

         Day Coffee Type  Units Sold  new_price
0     Monday    Espresso          25       3.99
1     Monday       Latte          15       5.99
2    Tuesday    Espresso          30       3.99
3    Tuesday       Latte          20       5.99
4  Wednesday    Espresso          35       3.99

If we actually want to modify the dataframe, we need to set inplace=True:

In [11]:
# coffee.drop(columns=['price'], inplace=True)
# coffee.head()

Alternatively, we can also do df = df.drop(...) without inplace=True:

In [12]:
#coffee = coffee.drop(columns=['price'])
#coffee.head()

A different way to drop columns is to just specify the columns we do want to keep. This is not recommended if we have a lot of columns we want to keep.

In [13]:
coffee = coffee[['Day', 'Coffee Type', 'Units Sold', 'new_price']]

In [14]:
coffee.head()

         Day Coffee Type  Units Sold  new_price
0     Monday    Espresso          25       3.99
1     Monday       Latte          15       5.99
2    Tuesday    Espresso          30       3.99
3    Tuesday       Latte          20       5.99
4  Wednesday    Espresso          35       3.99

## Other Operations

We can also multiply columns or perform similar kinds of operations:

In [15]:
coffee['revenue'] = coffee['Units Sold'] * coffee['new_price']
coffee.head()

         Day Coffee Type  Units Sold  new_price  revenue
0     Monday    Espresso          25       3.99    99.75
1     Monday       Latte          15       5.99    89.85
2    Tuesday    Espresso          30       3.99   119.70
3    Tuesday       Latte          20       5.99   119.80
4  Wednesday    Espresso          35       3.99   139.65

We can rename columns, too. Remember to use inplace=True or assignment to ensure your changes persist:

In [16]:
coffee.rename(columns={'new_price': 'price'}, inplace=True)
coffee.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso          25   3.99    99.75
1     Monday       Latte          15   5.99    89.85
2    Tuesday    Espresso          30   3.99   119.70
3    Tuesday       Latte          20   5.99   119.80
4  Wednesday    Espresso          35   3.99   139.65

We can use string operations to create new columns, too:

In [17]:
olympics_bios = pd.read_excel('https://github.com/KeithGalli/complete-pandas-tutorial/raw/refs/heads/master/data/olympics-data.xlsx', sheet_name=['bios'])
bios_new = olympics_bios['bios'].copy() # We do not necessarily need to use deep_copy

In [18]:
bios_new['first_name'] = bios_new['name'].str.split(' ').str[0]
bios_new['last_name'] = bios_new['name'].str.split(' ').str[1]
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,last_name
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,Blanchy
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,Boetsch
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,Borotra
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,Brugnon
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,Canet

In [19]:
bios_new.query('first_name =="Sophie"').head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,last_name
19566,19705,Sophie von Weiler,1958-12-24,NaN,NaN,NaN,Netherlands,159.0,62.0,NaN,Sophie,von
20495,20640,Sophie Moressée-Pichot,1962-04-03,Sissonne,Aisne,FRA,France,174.0,63.0,NaN,Sophie,Moressée-Pichot
45527,45872,Sophie Simard,1978-09-20,NaN,NaN,NaN,Canada,168.0,61.0,NaN,Sophie,Simard
46389,46737,Sophie Kamoun,1967-06-08,NaN,NaN,NaN,France,173.0,55.0,NaN,Sophie,Kamoun
60479,60912,Sophie Berge,1964-07-05,Nantes,Loire-Atlantique,FRA,France,171.0,65.0,NaN,Sophie,Berge

It is often recommended to turn dates into datetime objects. This can be done using pd.to_datetime. You can also set specific date formats.

In [20]:
bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date'], format="%Y-%m-%d")
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,last_name,born_datetime
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,Blanchy,1886-12-12
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,Boetsch,1969-04-01
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,Borotra,1898-08-13
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,Brugnon,1895-05-11
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,Canet,1878-04-17

In [21]:
bios_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   athlete_id     145500 non-null  int64
 1   name           145500 non-null  object
 2   born_date      143693 non-null  object
 3   born_city      110908 non-null  object
 4   born_region    110908 non-null  object
 5   born_country   110908 non-null  object
 6   NOC            145499 non-null  object
 7   height_cm      106651 non-null  float64
 8   weight_kg      102070 non-null  float64
 9   died_date      33940 non-null   object
 10  first_name     145500 non-null  object
 11  last_name      145500 non-null  object
 12  born_datetime  143693 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(9)
memory usage: 14.4+ MB

We can now extract the year from our new column of datetime objects using dt.year. By default the years will be floats.

In [22]:
bios_new['born_year'] = bios_new['born_datetime'].dt.year
bios_new[['name', 'born_year']].head()

                    name  born_year
0  Jean-François Blanchy     1886.0
1         Arnaud Boetsch     1969.0
2           Jean Borotra     1898.0
3        Jacques Brugnon     1895.0
4           Albert Canet     1878.0

In [23]:
bios_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 14 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   athlete_id     145500 non-null  int64
 1   name           145500 non-null  object
 2   born_date      143693 non-null  object
 3   born_city      110908 non-null  object
 4   born_region    110908 non-null  object
 5   born_country   110908 non-null  object
 6   NOC            145499 non-null  object
 7   height_cm      106651 non-null  float64
 8   weight_kg      102070 non-null  float64
 9   died_date      33940 non-null   object
 10  first_name     145500 non-null  object
 11  last_name      145500 non-null  object
 12  born_datetime  143693 non-null  datetime64[ns]
 13  born_year      143693 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(9)
memory usage: 15.5+ MB

We can save our new csv with to_csv. We can set index=False to avoid saving it with the additional index column.

In [24]:
bios_new.to_csv('bios_new.csv', index=False)

## Applying custom functions

In [25]:
olympics_bios = olympics_bios['bios']

We can write lambda functions and apply them:

In [26]:
olympics_bios['height_category'] = olympics_bios['height_cm'].apply(lambda x: 'Short' if x < 165 else ('Average' if x < 185 else 'Tall'))

In [27]:
olympics_bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall
...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Average
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Average
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Short
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,Average
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Tall

We can also define regular functions and apply them.

axis=0 means we apply the function on the column axis, but axis=1 means we apply it on the row axis.

In [28]:
def categorise_athlete(row):
  if row['height_cm'] < 175 and row['weight_kg'] < 70:
    return 'Lightweight'
  elif row['height_cm'] < 185 or row['weight_kg'] <= 85:
    return 'Middleweight'
  else:
    return 'Heavyweight'

olympics_bios['Category'] = olympics_bios.apply(categorise_athlete, axis=1)

In [29]:
olympics_bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,Middleweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,Middleweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,Lightweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavyweight