<a href="https://colab.research.google.com/github/sselgrad23/Pandas-Tutorial-For-Beginners/blob/main/pandas_tutorial_lesson_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Merging and Concatenating Data

In [1]:
import pandas as pd

In [2]:
olympics_bios = pd.read_excel('https://github.com/KeithGalli/complete-pandas-tutorial/raw/refs/heads/master/data/olympics-data.xlsx', sheet_name=['bios'])['bios']

In [3]:
nocs = pd.read_csv('https://github.com/KeithGalli/complete-pandas-tutorial/raw/refs/heads/master/data/noc_regions.csv')

In [4]:
nocs.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [5]:
olympics_bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

Check documentation for the different ways to merge two datasets.

*   `left_on`: The column from the left DataFrame to use as a key.
*   `right_on`: The column from the right DataFrame to use as a key.
*   Different types of joins: `inner` (default), `left`, `right`, `outer`.

By default, if two columns in two dataframes have the same column name, the column of the left dataframe will receive the `_x` suffix and the right dataframe will receive the `_y` suffix. You can provide custom suffixes using `suffixes=[...]`.

In [6]:
bios = pd.merge(olympics_bios, nocs, left_on='born_country', right_on='NOC', how='left', suffixes=["bios", "nocs"])
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOCbios,height_cm,weight_kg,died_date,NOCnocs,region,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,GBR,UK,NaN

In [7]:
bios.rename(columns={'region': 'born_country_full'}, inplace=True) # renaming the columns
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOCbios,height_cm,weight_kg,died_date,NOCnocs,born_country_full,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,GBR,UK,NaN

Here is how we can extract the rows where NOCbios and born_country_full aren't the same:

In [8]:
bios[bios['NOCbios'] != bios['born_country_full']][['name', 'NOCbios', 'born_country_full']]

                       name  NOCbios born_country_full
4              Albert Canet   France                UK
12                J. Defert   France               NaN
13           Étienne Durand   France               NaN
16               Guy Forget   France           Morocco
27       Guy, Baron Lejeune   France               NaN
...                     ...      ...               ...
145491        Matthew Wepke  Jamaica               NaN
145493   Landysh Falyakhova      ROC            Russia
145495    Polina Luchnikova      ROC            Russia
145496  Valeriya Merkusheva      ROC            Russia
145497      Yuliya Smirnova      ROC            Russia

[73210 rows x 3 columns]

We can extract athletes from certain countries in the following manner:

In [9]:
usa = bios[bios['born_country'] == 'USA'].copy()
gbr = bios[bios['born_country'] == 'GBR'].copy()

In [10]:
usa.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOCbios,height_cm,weight_kg,died_date,NOCnocs,born_country_full,notes
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN,USA,USA,NaN
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN,USA,USA,NaN
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN,USA,USA,NaN
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20,USA,USA,NaN
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN,USA,USA,NaN

In [11]:
gbr.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOCbios,height_cm,weight_kg,died_date,NOCnocs,born_country_full,notes
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,GBR,UK,NaN
37,38,Helen Aitchison,1881-12-06,Sunderland,England,GBR,Great Britain,NaN,NaN,1947-05-26,GBR,UK,NaN
38,39,Geraldine Beamish,1883-06-23,Forest Gate,England,GBR,Great Britain,NaN,NaN,1972-05-10,GBR,UK,NaN
39,40,Dora Boothby,1881-08-02,Finchley,England,GBR,Great Britain,NaN,NaN,1970-02-22,GBR,UK,NaN
40,41,Julie Bradbury,1967-02-12,Oxford,England,GBR,Great Britain,175.0,64.0,NaN,GBR,UK,NaN

To concatenate these two dataframes:

In [12]:
usa_gbr = pd.concat([usa, gbr])

In [13]:
usa_gbr.tail()

,athlete_id,name,born_date,born_city,born_region,born_country,NOCbios,height_cm,weight_kg,died_date,NOCnocs,born_country_full,notes
144811,148512,Benjamin Alexander,1983-05-08,London,England,GBR,Jamaica,NaN,NaN,NaN,GBR,UK,NaN
144815,148517,Ashley Watson,1993-10-28,Peterborough,England,GBR,Jamaica,NaN,NaN,NaN,GBR,UK,NaN
145005,148716,Peder Kongshaug,2001-08-13,Wimbledon,England,GBR,Norway,184.0,86.0,NaN,GBR,UK,NaN
145319,149041,Axel Brown,1992-04-02,Harrogate,England,GBR,Trinidad and Tobago,NaN,NaN,NaN,GBR,UK,NaN
145388,149111,Jean-Luc Baker,1993-10-07,Burnley,England,GBR,United States,NaN,NaN,NaN,GBR,UK,NaN

Finally, let's merge both the bios and the results of our Olympics dataset together. The `on='athlete_id'` parameter specifies that the merge should be performed using the common column 'athlete_id' present in both DataFrames. This ensures that the results are joined correctly for each unique athlete.

In [14]:
results = pd.read_csv('https://github.com/KeithGalli/complete-pandas-tutorial/raw/refs/heads/master/data/results.csv')
combined = pd.merge(bios, results, on='athlete_id', how='left')

In [15]:
combined.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOCbios,height_cm,weight_kg,died_date,...,year,type,discipline,event,as,noc,team,place,tied,medal
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,...,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,FRA,NaN,17.0,True,NaN
1,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,...,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,FRA,Jean Montariol,NaN,False,NaN
2,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,...,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,FRA,NaN,32.0,True,NaN
3,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,...,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,FRA,Jeanne Vaussard,8.0,True,NaN
4,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,...,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,FRA,Jacques Brugnon,4.0,False,NaN