<a href="https://colab.research.google.com/github/sselgrad23/Pandas-Tutorial-For-Beginners/blob/main/pandas_tutorial_lesson_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Loading Dataframes From Different File Formats

In [31]:
import pandas as pd

All datasets used here are courtesy of Keith Galli: https://github.com/KeithGalli/complete-pandas-tutorial

Pandas can read CSV files from URLs, which is useful for Google Colab. If you have the CSV file stored locally, e.g. in './warmup_data/coffee.csv',
then you can use pd.read_csv('./warmup_data/coffee.csv')

In [32]:
# Courtesy of Keith Galli
coffee = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv')

In [33]:
coffee.head() # First five rows of coffee dataframe

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

CSV is a popular file format for storing data as they can be easily read by humans. However, CSV files can take up a lot of storage. Other popular file formats like .feather and .parquet are generally more efficient in terms of storage and performance.

Below, we read a feather file:

In [34]:
feather_results = pd.read_feather('https://github.com/KeithGalli/complete-pandas-tutorial/raw/refs/heads/master/data/results.feather')

In [35]:
feather_results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None

Reading a parquet file:

In [36]:
parquet_results = pd.read_parquet('https://github.com/KeithGalli/complete-pandas-tutorial/raw/refs/heads/master/data/results.parquet')

In [37]:
parquet_results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None

We can even read Excel spreadsheets (.xlsx files), as shown below.

However, .xlsx files are also not ideal for large datasets, especially when it comes to storage size and read/write performance compared to binary formats like Feather or Parquet.

They are designed for a broader range of functionality, including formatting, formulas, and multiple sheets. This adds overhead not present in the previously seen simpler file formats.

In [38]:
olympics_data = pd.read_excel('https://github.com/KeithGalli/complete-pandas-tutorial/raw/refs/heads/master/data/olympics-data.xlsx')

In [39]:
olympics_data.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

This spreadsheet has two sheets, bios and results. By default, pandas will read the first sheet, bios. If we want to read specific sheets, then we have to do the following:

In [40]:
olympics_data_sheets = pd.read_excel('https://github.com/KeithGalli/complete-pandas-tutorial/raw/refs/heads/master/data/olympics-data.xlsx', sheet_name=['bios', 'results'])

In [41]:
olympics_data_sheets.keys() # This tells us which sheets we have

dict_keys(['bios', 'results'])

In [42]:
olympics_data_sheets['bios'].head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [43]:
olympics_data_sheets['results'].head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

We can also convert dataframes into different file formats.

In [44]:
bios = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/master/data/bios.csv')

In [45]:
bios.to_csv('bios.csv')

In [46]:
bios.to_excel('bios.xlsx')

In [47]:
bios.to_feather('bios.feather')

In [48]:
bios.to_parquet('bios.parquet')